name: lint

"on":
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwaldowski/cspell-action@v1
        with:
          config: .cspell.json
          paths: "**/*.md"
